method: bayes
metric:
  goal: maximize
  name: accuracy
parameters:
  batch_size:
    values: [1024, 2048, 3072, 4096]
  opt:
    values: ["nadamw", "adamw", "lamb"]
  lr:
    min: 0.0001
    max: 0.005
    distribution: uniform
  min_lr:
    min: 5e-7
    max: 1e-4
    distribution: uniform
  warmup_epochs:
    min: 5
    max: 20
    distribution: q_uniform
    q: 5
  weight_decay:
    min: -6.90775
    max: -2.30258
    distribution: log_uniform
  drop_path:
    min: 0.01
    max: 0.1
    distribution: uniform
  shortcut_gain:
    value: 1.0
    distribution: constant
#    min: -2.30258
#    max: 0.13976
#    distribution: q_log_uniform
#    q: 0.1
early_terminate:
  type: hyperband
  min_iter: 100
  max_iter: 200
  eta: 3